# Generated by Django 3.0.8 on 2020-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RBCDetectParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('param2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('minDist', models.IntegerField()),
                ('minRad', models.IntegerField()),
                ('maxRad', models.IntegerField()),
            ],
        ),
    ]
