# Generated by Django 3.0.8 on 2020-08-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbcdetectparams',
            name='param1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rbcdetectparams',
            name='param2',
            field=models.FloatField(),
        ),
    ]
